---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis-pod
    tier: ject
spec:
  containers:
    - name: redis-app
      image: redis
      ports:
        - containerPort: 80
...