---
apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    name: voting-pod
    app: ject
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80
...